/* Auto-generated by genmsg_cpp for file /home/kevinseidel/ros/kurt_msgs/msg/Encoder.msg */
#ifndef KURT_MSGS_MESSAGE_ENCODER_H
#define KURT_MSGS_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kurt_msgs
{
template <class ContainerAllocator>
struct Encoder_ {
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
  : header()
  , left(0)
  , right(0)
  {
  }

  Encoder_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , left(0)
  , right(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _left_type;
  int32_t left;

  typedef int32_t _right_type;
  int32_t right;


  typedef boost::shared_ptr< ::kurt_msgs::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kurt_msgs::Encoder_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Encoder
typedef  ::kurt_msgs::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::kurt_msgs::Encoder> EncoderPtr;
typedef boost::shared_ptr< ::kurt_msgs::Encoder const> EncoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kurt_msgs::Encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kurt_msgs::Encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kurt_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kurt_msgs::Encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kurt_msgs::Encoder_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kurt_msgs::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1b78a4027c07bd9a8a89543455494fb2";
  }

  static const char* value(const  ::kurt_msgs::Encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1b78a4027c07bd9aULL;
  static const uint64_t static_value2 = 0x8a89543455494fb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kurt_msgs::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kurt_msgs/Encoder";
  }

  static const char* value(const  ::kurt_msgs::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kurt_msgs::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 left\n\
int32 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kurt_msgs::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kurt_msgs::Encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kurt_msgs::Encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kurt_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kurt_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kurt_msgs::Encoder_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KURT_MSGS_MESSAGE_ENCODER_H

